# <span style="color:rgb(160,0,86)">Datenbeschreibung</span>

***

## <span style="color:rgb(160,0,86)">Lernziele</span>

- Sie können absolute und relative Häufigkeiten und Summenhäufigkeiten berechnen und verstehen ihre Bedeutung.
- Sie kennen Lagemasse und Streumasse für nominale, ordinale und metrische Merkmale und können sie berechnen.  

***

### <span style="color:rgb(160,0,86)">Was ist eine Häufigkeitsanalyse?</span>

Die grundlegendste Aufbereitung statistischer Daten ist die Darstellung, wie häufig die Ausprägungen eines Merkmals vorkommen. 

- Die **absolute Häufigkeit** $n(x)$ ist die Anzahl, wie oft ein Wert $x$ vorkommt.
- Die **relative Häufigkeit** $h(x)=\displaystyle\frac{n(x)}{n}$ ist der Anteil, mit dem ein Wert $x$ vorkommt. 

Weil *oridinale* und *metrische* Merkmalen eine Reihenfolge haben, können wir Häufigkeiten auch der Reihe nach kumulieren:

- Die **absolute Summenhäufigkeit** $N(x)$ ist die Anzahl, wie oft Werte kleiner oder gleich $x$ vorkommen.
- Die **relative Summenhäufigkeit** $H(x)=\displaystyle\frac{N(x)}{n}$ ist der Anteil, mit dem Werte kleiner oder gleich $x$ vorkommen.

Die Auflistung aller Werte $x_1, x_2, \ldots, x_m$ eines Merkmals zusammen mit ihren Häufigkeiten nennen wir eine **empirische Häufigkeitsverteilung**.

*Merke:* Aus der empirischen Häufigkeitsverteilung können wir nicht mehr herauslesen, was für einen Wert eine statistische Einheit bei einem Merkmal hat. Wir sehen nur noch, wie oft oder wie häufig die Werte eines Merkmals vorkommen. **Es geht Information verloren!** 

***

#### <span style="color:rgb(160,0,86)">Beispiel:</span>

Betrachten wir 10 ehemalige Studierende mit den Merkmalen **Geschlecht**, **Gesamtprädikat** und **Alter**:

$$\begin{bmatrix}
\text{Anna}&w&\text{ausgezeichnet}&27\\
\text{Beat}&m&\text{gut}&34\\
\text{Cary}&m&\text{sehr gut}&29\\
\text{Dana}&w&\text{sehr gut}&24\\
\text{Elif}&w&\text{gut}&25\\
\text{Faro}&m&\text{ausgezeichnet}&27\\
\text{Gabi}&w&\text{sehr gut}&27\\
\text{Hans}&m&\text{genügend}&69\\
\text{Ivea}&w&\text{sehr gut}&26\\
\text{Jose}&w&\text{gut}&31
\end{bmatrix}$$

In [ ]:
namen = ["Anna", "Beat", "Cary", "Dana", "Elif", "Faro", "Gabi", "Hans", "Ivea", "Jose"]
geschlecht = ["w", "m", "m", "w", "w", "m", "w", "m", "w", "w"]
prädikat = ["ausgezeichnet", "gut", "sehr gut", "sehr gut", "gut", "ausgezeichnet", "sehr gut", "genügend", "sehr gut",
            "gut"]
alter = [27, 34, 29, 24, 25, 27, 27, 69, 26, 31]

import pandas as pd

df = pd.DataFrame({"Name": namen, "Geschlecht": geschlecht, "Prädikat": prädikat, "Alter": alter})
df

Das Geschlecht ist ein nominales Merkmal. Seine empirische Verteilung ist:

In [2]:
import numpy as np

dim = df.shape
(werte, absH) = np.unique(df["Geschlecht"], return_counts=True)  # werte = "m","w" & absH absolute Anzahl 
for i in range(len(werte)):
    print("n(" + werte[i] + ") =", absH[i])
for i in range(len(werte)):
    print("h(" + werte[i] + ") =", absH[i] / dim[0])

n(m) = 4
n(w) = 6
h(m) = 0.4
h(w) = 0.6

Das Prädikat ist ein ordinales Merkmal. Seine empirische Verteilung ist:

In [3]:
werte, absH = np.unique(df["Prädikat"], return_counts=True)
werte

array(['ausgezeichnet', 'genügend', 'gut', 'sehr gut'], dtype=object)

In [4]:
for i in [1, 2, 3, 0]:
    print("n(" + werte[i] + ") =", absH[i])
for i in [1, 2, 3, 0]:
    print("h(" + werte[i] + ") =", absH[i] / dim[0])
#wie viele sind genügend oder kleiner
#wie viele sind gut oder kleiner etc.
#ausgezeichnet is also = alle Elemente

n(genügend) = 1
n(gut) = 3
n(sehr gut) = 4
n(ausgezeichnet) = 2
h(genügend) = 0.1
h(gut) = 0.3
h(sehr gut) = 0.4
h(ausgezeichnet) = 0.2

In [5]:
absSH = 0
for i in [1, 2, 3, 0]:
    absSH += absH[i]
    print("N(" + werte[i] + ") =", absSH)
absSH = 0
for i in [1, 2, 3, 0]:
    absSH += absH[i]
    print("H(" + werte[i] + ") =", absSH / dim[0])

N(genügend) = 1
N(gut) = 4
N(sehr gut) = 8
N(ausgezeichnet) = 10
H(genügend) = 0.1
H(gut) = 0.4
H(sehr gut) = 0.8
H(ausgezeichnet) = 1.0

Das Alter ist ein metrisches Merkmal. Seine empirische Verteilung ist:

In [6]:
werte, absH = np.unique(df["Alter"], return_counts=True)
for i in range(len(werte)):
    print("n(" + str(werte[i]) + ") =", absH[i])
for i in range(len(werte)):
    print("h(" + str(werte[i]) + ") =", absH[i] / dim[0])

n(24) = 1
n(25) = 1
n(26) = 1
n(27) = 3
n(29) = 1
n(31) = 1
n(34) = 1
n(69) = 1
h(24) = 0.1
h(25) = 0.1
h(26) = 0.1
h(27) = 0.3
h(29) = 0.1
h(31) = 0.1
h(34) = 0.1
h(69) = 0.1

In [7]:
def summenhaeufigkeit(w, h, x):
    N = 0
    i = 0
    while i < len(w) and w[i] <= x:
        N += h[i]
        i += 1
    return N, (N / sum(h))


summenhaeufigkeit(werte, absH, 30)  #wie viele sind jünger als x

(np.int64(7), np.float64(0.7))

### <span style="color:rgb(160,0,86)">Was sind Lagemasse und Streumasse?</span>

Die empirische Häufigkeitsverteilung beantwortet die Frage: Wie oft kommen die Werte eines Merkmals vor? Mit **statistischen Masszahlen** sollen nun spezifische Informationen aus den Daten herausgefiltert werden.      

- Ein **Lagemass** beschreibt mit einem typischen Wert, *wo* die Ausprägungen eines Merkmals liegen.
- Ein **Streumass** beschreibt mit einem typischen Wert, *wie* unterschiedlich die Ausprägungen eines Merkmals sind.

#### <span style="color:rgb(160,0,86)">Für nominale Merkmale:</span>
- *Lagemass:* Weil die Werte keine natürliche Reihenfolge haben, können wir keine *Mitte* festlegen. Als repräsentativer Wert für die Lage der Werte wird oft der häufigste Wert, der sogenannte **Modus** $\bar{x}_{D}$ angegeben.
- *Streumass:* Wir wollen angeben, wie gleichmässig sich die ungeordneten Werte verteilen. Wenn bei einem Merkmal nur ein Wert vorkommt, gibt es keine Streuung. Wenn hingegen alle Werte eines Merkmals gleich häufig auftreten, gibt es maximale Unterschiedlichkeit. Als Mass für diese Charakteristik wird häufig der **Dispersionsindex** $$P = \displaystyle\frac{m}{m-1}\big(h(x_1)\cdot(1-h(x_1))+h(x_2)\cdot(1-h(x_2))+\ldots+h(x_m)\cdot(1-h(x_m)\big)$$ gebraucht. Wenn $P>0.9$ ist, haben wir starke Dispersion und wenn $P<0.8$ ist, haben wir geringe Dispersion. Wenn im Extremfall ein Wert eine relative Häufigkeit von 1.0 hat, dann ist $P=1$ und wenn alle Werte die gleiche relative Häufigkeit haben, dann ist $P=0$.

In [8]:
werte, absH = np.unique(df["Geschlecht"], return_counts=True)
m = len(werte)
relH = absH / dim[0]
modus = df["Geschlecht"].mode()[0]
P = m / (m - 1) * sum(relH * (1 - relH))
print("x_D =", modus, ", P =", P)

x_D = w , P = 0.96

$P = \displaystyle\frac{2}{2-1}\big(0.4\cdot(1-0.4)+0.6\cdot(1-0.6)\big)=0.96$

#### <span style="color:rgb(160,0,86)">Für ordinale Merkmale:</span>
- *Lagemass:* Die Werte haben eine natürliche Reihenfolge Wir können aber mit diesen Werten im allgemeinen nicht rechnen. Wenn wir die Daten aufsteigend der Reihe nach sortieren, können wir das sogenannte $p$ **-Quantil** bestimmen. Das ist ein Wert $x_p$, der die Daten in einen unteren Teil und in einen oberen Teil unterteil: $p\%$ der Daten sind kleiner oder gleich als $x_p$ und $(1-p)\%$ der Daten sind grösser. Mit $p=50\%$ sind in beiden Teilen ungefähr gleich viele Daten, daher heisst $x_{50\%}$ der **Median**. Der Wert $x_{25\%}$ heisst **unteres Quartil**, weil ungefähr ein viertel der Daten kleiner als $x_{25\%}$ sind und der Wert $x_{75\%}$ heisst **oberes Quartil**, weil ungefähr drei viertel der Daten kleiner als $x_{75\%}$ sind.      
- *Streumass:* Wegen der natürlichen Reihenfolge können wir die Streuung differnzierter beschreiben. Streuung ist gross, wenn die Werte gleichmässig beim *kleinsten* und beim *grössten* Wert des Merkmals liegen. Als Mass für diese Charakteristik wird häufig die **Diversität** $$D = \displaystyle\frac{4}{m-1}\big(H(x_1)\cdot(1-H(x_1))+H(x_2)\cdot(1-H(x_2))+\ldots+H(x_m)\cdot(1-H(x_m)\big)$$ gebraucht. Wenn $D>0.8$ ist, haben wir starke Diversität und wenn $D<0.6$ ist, haben wir geringe Diversität. Wenn im Extremfall ein Wert eine relative Häufigkeit von 1.0 hat, dann ist $D=0$ und wenn 50% der Daten beim kleinsten und 50% der Daten beim grössten Wert liegen, dann ist $D=1$.

In [9]:
werte, absH = np.unique(df["Prädikat"], return_counts=True)
m = len(werte)
werte = np.array([werte[1], werte[2], werte[3], werte[0]])
absH = np.array([absH[1], absH[2], absH[3], absH[0]])
relH = absH / dim[0]
relSH = np.array([relH[0], sum(relH[:2]), sum(relH[:3]), sum(relH)])
modus = df["Prädikat"].mode()[0]
median = werte[0]
i = 1
while i <= m:
    if relSH[i] > 0.5:
        break
    median = werte[i]
    i += 1
D = 4 / (m - 1) * sum(relSH * (1 - relSH))
print("x_D =", modus, ", median =", median, ", D =", D)

x_D = sehr gut , median = gut , D = 0.6533333333333333

$D = \displaystyle\frac{4}{4-1}\big(0.1\cdot(1-0.1)+0.4\cdot(1-0.4)+0.8\cdot(1-0.8)+1.0\cdot(1-1.0)\big)=0.65\bar{3}$

#### <span style="color:rgb(160,0,86)">Für metrische Merkmale:</span>
- *Lagemass:* Da wir mit den Werten rechnen können, lässt sich die Summe aller Daten gleichmässig auf alle statistischen Einheiten verteilen. Dieses **arithmetische Mittel** $\bar{x}$ beschreibt, wie gross die Werte im Mittel sind. Das arithmetische Mittel wird aber von einzelnen extremen Werten stark beeinflusst. Der Median hingegen wird von extremen Werten weniger beeinflusst, weil sehr grosse oder sehr kleine Werte die Reihenfolge in der Mitte nicht verändern.
- *Streumass:* Bei metrischen Daten sind die Quartile auch Zahlen. Daher können wir den **Qartilsabstand** $Q = x_{75\%}-x_{25\%}$ vom unteren Quartil zum oberen Quartil berechnen. In diesem Bereich liegen ungefähr 50\% der mittleren Danten. Wenn also $Q$ klein ist, dann liegen die Daten eng beieinander und wenn $Q$ gross ist, dann streuen die Daten stark. Der Quartilsabstand wird durch extreme Werte auch nicht gross beeinflusst.<br>
Eine anderes Mass für die Streuung ist die **mittlere Abweichung** $MD$ der Daten vom arithmetischen Mittel $$MD=\displaystyle\frac{1}{n}\big(|x_1-\bar{x}|+|x_2-\bar{x}|+\ldots+|x_n-\bar{x}|\big)\,.$$ Weil die Absolutbeträge technische Schwierigkeiten mit sich bringen, werden häufiger die **mittlere quadratische Abweichung** $MQD$ der Daten vom arithmetischen Mittel $$MQD=\displaystyle\frac{1}{n}\big((x_1-\bar{x})^2+(x_2-\bar{x})^2+\ldots+(x_n-\bar{x})^2\big)$$ gebraucht. Dieser Wert hat den Nachteil, dass die Dimension nicht mehr stimmt. Die Zahl $MQD$ hat quadratische Einheiten. Wenn wir aber aus $MQD$ die Wurzel zeihen, erhalten wir die sogenannte **Standardabweichung** $$s=\sqrt{MQD}\;,$$ bei der die Dimension wieder stimmt.

In [10]:
q50 = df["Alter"].median()
x_bar = df["Alter"].mean()
Q = df["Alter"].quantile(0.75) - df["Alter"].quantile(0.25)
s = df["Alter"].std(ddof=0)
MD = sum(np.abs(df["Alter"] - x_bar)) / len(df["Alter"])
print("Median =", q50, ", arithmetisches Mittel =", x_bar)
print("Q =", Q, ", s =", s, ", MD =", MD)

Median = 27.0 , arithmetisches Mittel = 31.9
Q = 4.25 , s = 12.676355943251199 , MD = 7.840000000000001

### <span style="color:rgb(160,0,86)">Aufgabe 1</span>

Laden Sie die Daten *2021_Personalerhebung.csv* und bestimmen Sie für alle Merkmale passende Lagemasse und Streumasse. Bestimmen Sie auch für die Merkmale **Abteilung** und **Ausbildung** die relativen Häufigkeiten und relativen Summenhäufigkeiten.

In [11]:
person_data = pd.read_csv("./Daten/2021_Personalerhebung.csv", delimiter=";")
person_data.drop(person_data.columns[1], axis=1, inplace=True)
person_data

    PersNummer         Abteilung      Ausbildung  Eintrittsjahr  Bruttogehalt
0       560426          Finanzen          Abitur           2006         13200
1       590303          Vertrieb  Mittlere Reife           2008         13500
2       611117       Entwicklung       Promotion           2008         17600
3       620212  Geschaftsführung          Master           2006         18000
4       620624       Entwicklung          Master           2007         17400
5       640530  Geschaftsführung  Mittlere Reife           2009          7200
6       681212       Entwicklung        Bachelor           2009         10800
7       700525  Test/Anwendungen        Bachelor           2010          7200
8       711204  Geschaftsführung        Bachelor           2007         13600
9       730119          Finanzen        Bachelor           2009          9600
10      730523       Entwicklung          Master           2010          7400
11      730526          Schulung       Promotion           2009         18200
12      741222          Vertrieb          Abitur           2008          9600
13      750227  Geschaftsführung  Mittlere Reife           2010          2800
14      750705          Schulung          Master           2009          9200
15      760104  Test/Anwendungen        Bachelor           2010          5000
16      760930       Entwicklung        Bachelor           2010          4800
17      780522          Finanzen          Abitur           2010          6400
18      780920       Entwicklung          Master           2010          5400
19      790820       Entwicklung        Bachelor           2010          6800
20      791112          Schulung        Bachelor           2010          2400
21      811030  Test/Anwendungen          Abitur           2010          2000
22      870512          Vertrieb        Bachelor           2010          5500
23      850621          Vertrieb          Abitur           2010          4000
24      890323  Test/Anwendungen          Abitur           2010          3400

In [12]:

def calc_rel_sh(relH):
    relSH = np.empty(len(relH))
    for i in range(len(relH)):
        relSH[i] = sum(relH[range(0, i + 1)])
    return relSH


def calc_median(werte):
    i = 0
    median = werte[0]
    while i <= n:
        if relSH[i] > 0.5:
            break
        i += 1
        median = werte[i]
    return median


def calc_diversity(m, relSH):
    return round(4 / (m - 1) * sum(relSH * (1 - relSH)), 4)


def calc_dispersion(m, relH):
    return round(m / (m - 1) * sum(relH * (1 - relH)), 4)


def print_nominal(relH, modus, dispersion):
    print("relative Häufigkeiten=", relH, ", Lagemass (modus)=", modus, ", Streumass (Dispersionsindex)=", dispersion)


def print_ordial(relH, relSH, median, diversity):
    print("relative Häufigkeiten=", relH,
          ", relative Summenhäufigkeit", relSH,
          ", Lagemass (median)=", median,
          ", Streumass (Diversitätsindex)=", diversity)


def print_metric(mean, median, quartilsabstand, standard_deviation, md):
    print("Durchschnitt=", mean,
          ", Median=", median,
          ", Quartilsabstand=", quartilsabstand,
          ", Standardabweichung=", standard_deviation,
          ", Mittlere Abweichung=", md)

Abteilung:

In [13]:
dim = person_data.shape
abteilung = person_data["Abteilung"]
werte, absH = np.unique(abteilung, return_counts=True)
n = len(werte)
relH = absH / dim[0]
modus = abteilung.mode()[0]
dispersion = calc_dispersion(m, relH)

print_nominal(relH, modus, dispersion)

relative Häufigkeiten= [0.28 0.12 0.16 0.12 0.16 0.16] , Lagemass (modus)= Entwicklung , Streumass (Dispersionsindex)= 1.088

Ausbildung:

In [14]:
ausbildung = person_data["Ausbildung"]
werte, absH = np.unique(ausbildung, return_counts=True)
n = len(werte)
relH = absH / dim[0]
werte = np.array([werte[3], werte[0], werte[1], werte[2], werte[4]])
relSH = calc_rel_sh(relH)

median = calc_median(werte)
diversity = calc_diversity(n, relSH)

print_ordial(relH, relSH, median, diversity)

relative Häufigkeiten= [0.24 0.36 0.2  0.12 0.08] , relative Summenhäufigkeit [0.24 0.6  0.8  0.92 1.  ] , Lagemass (median)= Abitur , Streumass (Diversitätsindex)= 0.656

Eintrittsjahr:

In [15]:
jahr = person_data["Eintrittsjahr"]
werte, absH = np.unique(jahr, return_counts=True)
n = len(werte)
relH = absH / dim[0]
relSH = calc_rel_sh(relH)
werte.sort()

median = calc_median(werte)
diversity = calc_diversity(n, relSH)

print_ordial(relH, relSH, median, diversity)

relative Häufigkeiten= [0.08 0.08 0.12 0.2  0.52] , relative Summenhäufigkeit [0.08 0.16 0.28 0.48 1.  ] , Lagemass (median)= 2010 , Streumass (Diversitätsindex)= 0.6592

Bruttogehalt:

In [104]:
bruttogehalt = person_data["Bruttogehalt"]
mean = bruttogehalt.mean()
median = bruttogehalt.median()
quartilsabstand = bruttogehalt.quantile(0.75) - bruttogehalt.quantile(0.25)
standard_deviation = round(bruttogehalt.std(ddof=0), 4)
md = sum(abs((bruttogehalt - mean))) / len(bruttogehalt)

print_metric(mean, median, quartilsabstand, standard_deviation, md)

Durchschnitt= 8840.0 , Median= 7200.0 , Quartilsabstand= 8200.0 , Standardabweichung= 5057.3511 , Mittlere Abweichung= 4276.8

### <span style="color:rgb(160,0,86)">Aufgabe 2</span>

Laden Sie die Daten *Gesundheitskosten.csv* und bestimmen Sie für alle Merkmale passende Lagemasse und Streumasse.

In [16]:
import numpy as np
import pandas as pd
df = pd.read_csv("./Daten/Gesundheitskosten.csv")
df.rename(columns={"Unnamed: 0": "Jahr"}, inplace=True)
df

,Jahr,Krankenhäuser,Sozialmedizin,Arztpraxen,Zahnmedizin,Andere,Unterstützer,Detailhandel,Prävention,Staat,Versicherer,Importe
0,1995,12618.01,5626.22,5426.39,2678.79,1850.24,539.26,4291.59,523.88,873.51,1412.37,216.10
1,1996,13190.23,5983.41,5679.40,2731.91,1952.40,530.95,4459.82,543.27,864.67,1613.91,222.72
2,1997,13306.79,6218.51,5889.70,2752.02,1972.85,510.27,4646.23,554.69,810.88,1654.12,228.30
3,1998,13733.42,6517.62,6245.69,2787.40,2077.57,573.09,4777.10,598.37,815.25,1718.39,233.29
4,1999,14276.61,6635.99,6510.67,2787.08,2165.11,586.25,4933.82,622.52,861.53,1712.13,238.48
5,2000,14902.55,7041.51,6783.89,2897.78,2236.26,609.89,5094.54,647.37,885.80,1725.30,247.56
6,2001,16139.77,7546.75,7114.71,2984.30,2380.98,630.13,5329.64,679.05,921.52,1769.76,257.39
7,2002,16990.83,8067.66,7225.76,3034.52,2474.02,657.33,5420.90,685.82,1050.68,1759.70,262.00
8,2003,17727.33,8374.88,7385.51,3137.89,2514.52,663.08,5768.62,701.56,1043.76,1835.71,275.65
9,2004,18220.54,8629.93,7816.69,3236.47,2749.30,752.58,5952.56,726.04,1040.98,1950.60,284.81
10,2005,18305.10,8899.17,8093.79,3310.32,2911.45,816.33,6010.93,753.18,1052.62,1945.42,289.82
11,2006,18534.87,9005.23,8149.75,3461.79,2982.44,791.19,5932.99,767.55,1076.92,2050.58,294.32
12,2007,19375.96,9516.85,8485.99,3617.13,3112.32,806.17,6088.94,796.30,1249.64,2119.38,305.09
13,2008,20709.05,9971.44,8952.58,3722.96,3247.21,884.11,6307.61,839.75,1331.96,2281.43,315.26
14,2009,21715.14,10487.97,9224.82,3777.95,3410.78,900.91,6628.99,873.40,1496.40,2315.03,325.85
15,2010,22458.32,10768.79,9374.59,3860.64,3646.08,901.70,6628.43,887.16,1286.88,2424.00,328.39
16,2011,23039.86,11301.46,9665.25,3894.57,3749.34,992.17,6559.18,917.56,1259.96,2487.28,376.06
17,2012,24285.57,11747.50,10026.82,3978.16,3930.25,1019.98,6578.90,926.57,1238.54,2404.24,375.91
18,2013,25341.26,12040.35,10695.47,4061.21,4136.83,1217.39,6622.68,963.88,1284.21,2347.64,407.10
19,2014,26177.93,12323.52,11251.11,4155.96,4412.69,1323.91,6669.36,1033.64,1262.90,2393.22,424.99
20,2015,27148.71,12641.98,12080.30,4067.89,4851.01,1417.34,6914.21,1039.90,1275.84,2462.53,484.94
21,2016,28459.00,12796.24,12654.02,4001.77,5320.83,1574.26,7112.84,1045.80,1304.73,2610.14,575.57
22,2017,29020.36,13143.86,13180.07,4224.67,5619.82,1689.15,7107.74,1054.15,1360.03,2642.33,600.82
23,2018,29462.47,13404.13,12080.72,4413.52,5797.66,1763.24,7343.74,1097.81,1506.48,2693.61,678.41
24,2019,30331.02,13630.97,12829.77,4501.75,6092.70,1831.63,7499.00,1030.90,1278.23,2796.98,648.90
25,2020,30872.64,13927.28,11984.54,4235.50,6165.87,1552.50,7596.31,1035.22,2442.03,2935.86,563.00

In [17]:
for columnName in df.columns[1:]:
    column = df[columnName]
    mean = round(column.mean(), 2)
    median = round(column.median(), 2)
    quartilsabstand = round(column.quantile(0.75) - column.quantile(0.25), 2)
    standard_deviation = round(column.std(ddof=0), 2)
    md = round(sum(abs((column - mean) / column)) / len(column), 2)
    print("columnName=", columnName)
    print_metric(mean, median, quartilsabstand, standard_deviation, md)
    print()

columnName= Krankenhäuser
Durchschnitt= 21013.21 , Median= 20042.5 , Quartilsabstand= 9616.23 , Standardabweichung= 5807.76 , Mittlere Abweichung= 0.26

columnName= Sozialmedizin
Durchschnitt= 9855.74 , Median= 9744.14 , Quartilsabstand= 4575.75 , Standardabweichung= 2616.08 , Mittlere Abweichung= 0.26

columnName= Arztpraxen
Durchschnitt= 9031.08 , Median= 8719.28 , Quartilsabstand= 3969.73 , Standardabweichung= 2383.18 , Mittlere Abweichung= 0.25

columnName= Zahnmedizin
Durchschnitt= 3550.54 , Median= 3670.04 , Quartilsabstand= 1049.49 , Standardabweichung= 579.64 , Mittlere Abweichung= 0.15

columnName= Andere
Durchschnitt= 3529.25 , Median= 3179.77 , Quartilsabstand= 1939.48 , Standardabweichung= 1355.26 , Mittlere Abweichung= 0.36

columnName= Unterstützer
Durchschnitt= 982.11 , Median= 850.22 , Quartilsabstand= 660.35 , Standardabweichung= 414.04 , Mittlere Abweichung= 0.39

columnName= Detailhandel
Durchschnitt= 6087.56 , Median= 6198.28 , Quartilsabstand= 1306.81 , Standardabweichung= 950.71 , Mittlere Abweichung= 0.14

columnName= Prävention
Durchschnitt= 820.97 , Median= 818.02 , Quartilsabstand= 333.4 , Standardabweichung= 179.55 , Mittlere Abweichung= 0.21

columnName= Staat
Durchschnitt= 1187.54 , Median= 1244.09 , Quartilsabstand= 334.83 , Standardabweichung= 324.07 , Mittlere Abweichung= 0.19

columnName= Versicherer
Durchschnitt= 2156.22 , Median= 2200.4 , Quartilsabstand= 690.68 , Standardabweichung= 411.5 , Mittlere Abweichung= 0.18

columnName= Importe
Durchschnitt= 363.87 , Median= 310.17 , Quartilsabstand= 161.98 , Standardabweichung= 139.0 , Mittlere Abweichung= 0.33

### <span style="color:rgb(160,0,86)">Aufgabe 3</span>

Laden Sie die Daten *2022_Mathematik 1 WiSo Urliste*. In dieser Excel Datei sind die Mathematik Prüfungsergebnisse von Studierenden an der Fakultät Wirschaft und Sozialwissenschaften der Universität Bern gespeichert. Alle Studierende haben die gleiche Prüfung geschrieben, nur die Reihenfolge der Aufgaben war in der Version A und Version B anders (siehe Angaben in den Zellen N3 und N4). Die Punkte für die 9 Aufgaben sind abhängig von der Version A und B also in den Spalten vertauscht!  Bestimmen Sie für jede Aufgabe passende Lagemasse und Streumasse für die Punkte.

In [18]:
import xlrd
df = pd.read_excel("./Daten/2022_Mathematik 1 WiSo Urliste.xls", header=4)
df.drop(columns=["Unnamed: 10", "Unnamed: 12", "Unnamed: 13"], inplace=True)
df.rename(columns={"Version 1. Teilprüfung": "Teilprüfung"}, inplace=True)
df.drop(df.tail(12).index, inplace=True)
df

,Nr.,Aufgabe 1,Aufgabe 2,Aufgabe 3,Aufgabe 4,Aufgabe 5,Aufgabe 6,Aufgabe 7,Aufgabe 8,Aufgabe 9,Teilprüfung
0,1,3.5,4.0,3.5,4.0,4.0,4.0,4.0,4.0,4.0,A
1,2,2.5,3.5,4.0,3.0,2.0,4.0,3.0,1.0,1.5,B
2,3,1.5,4.0,3.0,2.5,3.0,4.0,1.5,3.0,2.0,A
3,4,1.5,3.5,1.5,4.0,3.0,0.0,1.0,3.5,0.0,A
4,5,3.5,3.0,3.5,3.0,3.5,2.0,3.5,2.5,2.0,A
...,...,...,...,...,...,...,...,...,...,...,...
406,407,3.5,2.0,4.0,2.5,3.5,0.5,0.0,2.0,0.0,A
407,408,3.0,2.5,2.0,1.5,0.5,3.0,1.0,1.0,0.0,B
408,409,4.0,1.0,4.0,3.0,3.0,4.0,3.5,1.0,0.0,B
409,410,1.0,3.5,2.0,3.0,2.5,1.5,1.5,2.5,0.0,A
410,411,1.0,3.5,3.0,4.0,4.0,1.0,0.0,0.0,0.0,A

![HSLU](Bilder/LogoHSLU.png)